### ISSUE TITLE
Don`t show task "Extract Password from variable initial_root_password" in log on latest version role:

### ISSUE THREAD

**Issue by buluma** [buluma/ansible-role-gitlab#22]
Don`t show task "Extract Password from variable initial_root_password" in log on latest version role:

If use inventory
```
all:
  children:
    gitlab:
      hosts:
        "gitlab":
          ansible_host: "51.250.97.225"
  vars:
    gitlab_external_url: "https://gitlab.51.250.97.225.sslip.io"
    ansible_user:  ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    gitlab_letsencrypt: yes
    gitlab_letsencrypt_contact_emails:
      - you.email@gmail.com
    gitlab_letsencrypt_group: root
    gitlab_letsencrypt_key_size: 2048
    gitlab_letsencrypt_owner: root
    gitlab_letsencrypt_wwwroot: /var/opt/gitlab/nginx/www
    gitlab_letsencrypt_auto_renew: yes
    gitlab_letsencrypt_auto_renew_hour: 0
    gitlab_letsencrypt_auto_renew_minute: nil
    gitlab_letsencrypt_auto_renew_day_of_month: 7
    gitlab_letsencrypy_auto_renew_log_directory: /var/log/gitlab/lets-encrypt
    gitlab_initial_root_password: true
```

Playbook
```
- hosts: gitlab
  become: yes
  roles:
    - role: buluma.gitlab
```

Output
```
TASK [buluma.gitlab : place configuration static] **************************************************************************************************************************************
Monday 28 March 2022  12:04:07 +0600 (0:00:00.013)       0:06:12.160 **********
skipping: [gitlab]

RUNNING HANDLER [buluma.gitlab : run gitlab-ctl reconfigure] ***************************************************************************************************************************
Monday 28 March 2022  12:04:07 +0600 (0:00:00.016)       0:06:12.177 **********
changed: [gitlab]

RUNNING HANDLER [buluma.gitlab : uninstall ruby] ***************************************************************************************************************************************
Monday 28 March 2022  12:08:52 +0600 (0:04:44.438)       0:10:56.615 **********
changed: [gitlab]

PLAY RECAP *****************************************************************************************************************************************************************************
gitlab                     : ok=67   changed=8    unreachable=0    failed=0    skipped=45   rescued=0    ignored=0

Monday 28 March 2022  12:09:07 +0600 (0:00:14.739)       0:11:11.354 **********
===============================================================================
buluma.gitlab : install gitlab ------------------------------------------------------------------------------------------------------------------------------------------------ 311.87s
buluma.gitlab : run gitlab-ctl reconfigure ------------------------------------------------------------------------------------------------------------------------------------ 284.44s
buluma.gitlab : install requirements ------------------------------------------------------------------------------------------------------------------------------------------- 27.67s
buluma.gitlab : uninstall ruby ------------------------------------------------------------------------------------------------------------------------------------------------- 14.74s
buluma.gitlab : install apt repository ----------------------------------------------------------------------------------------------------------------------------------------- 13.17s
buluma.gitlab : install ruby to allow syntax check of gitlab.rb ----------------------------------------------------------------------------------------------------------------- 7.89s
Gathering Facts ----------------------------------------------------------------------------------------------------------------------------------------------------------------- 4.72s
buluma.gitlab : place configuration templated ----------------------------------------------------------------------------------------------------------------------------------- 2.89s
buluma.gitlab : install apt repository key -------------------------------------------------------------------------------------------------------------------------------------- 2.07s
buluma.gitlab : test if item in gitlab_rails_ldap_servers is set correctly ------------------------------------------------------------------------------------------------------ 0.06s
buluma.gitlab : test if gitlab_default_projects_feature_* are set correctly ----------------------------------------------------------------------------------------------------- 0.02s
buluma.gitlab : test if group_base item in gitlab_rails_ldap_servers is set correctly ------------------------------------------------------------------------------------------- 0.02s
buluma.gitlab : test if sync_ssh_keys item in gitlab_rails_ldap_servers is set correctly ---------------------------------------------------------------------------------------- 0.02s
buluma.gitlab : test if admin_group item in gitlab_rails_ldap_servers is set correctly ------------------------------------------------------------------------------------------ 0.02s
buluma.gitlab : test if gitlab_letsencrypt_auto_renew is set correctly ---------------------------------------------------------------------------------------------------------- 0.02s
buluma.gitlab : test if gitlab_rails_smtp_password is set correctly ------------------------------------------------------------------------------------------------------------- 0.02s
buluma.gitlab : test if gitlab_rails_gitlab_email_reply_to is set correctly ----------------------------------------------------------------------------------------------------- 0.02s
buluma.gitlab : test if gitlab_rails_db_host is set correctly ------------------------------------------------------------------------------------------------------------------- 0.02s
buluma.gitlab : test if gitlab_rails_smtp_authentication is set correctly ------------------------------------------------------------------------------------------------------- 0.02s
buluma.gitlab : test if gitlab_cleanup_ruby is set correctly -------------------------------------------------------------------------------------------------------------------- 0.02s
###############

```

_Originally posted by @patsevanton in https://github.com/buluma/ansible-role-gitlab/issues/21#issuecomment-1080237731_
